name: 'Setup Rust with cache'
inputs:
  rust-channel:
    description: 'Rust channel to install'
    required: false
    default: 'stable'
  save-cache:
    description: 'Whether to save the cache (only on main branch)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      run: |
        rustup component add --toolchain ${{ inputs.rust-channel }} rustfmt rust-src
        rustup update --no-self-update ${{ inputs.rust-channel }}
        rustup default ${{ inputs.rust-channel }}
      shell: bash

    - name: Get Rust cache key
      id: rust-cache
      shell: bash
      run: |
        echo "rust_version=$(rustc --version | awk '{print $2}')" >> $GITHUB_OUTPUT
        echo "cargo_lock_hash=${{ hashFiles('**/Cargo.lock') }}" >> $GITHUB_OUTPUT
        echo "cache_suffix=${{ inputs.save-cache == 'true' && '' || format('-{0}', github.run_id) }}" >> $GITHUB_OUTPUT

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-registry-${{ runner.os }}-${{ steps.rust-cache.outputs.rust_version }}-${{ steps.rust-cache.outputs.cargo_lock_hash }}${{ steps.rust-cache.outputs.cache_suffix }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-${{ steps.rust-cache.outputs.rust_version }}-${{ steps.rust-cache.outputs.cargo_lock_hash }}
          cargo-registry-${{ runner.os }}-${{ steps.rust-cache.outputs.rust_version }}-
          cargo-registry-${{ runner.os }}-

    - name: Cache cargo target
      uses: actions/cache@v4
      with:
        path: target
        key: cargo-target-${{ runner.os }}-${{ steps.rust-cache.outputs.rust_version }}-${{ steps.rust-cache.outputs.cargo_lock_hash }}${{ steps.rust-cache.outputs.cache_suffix }}
        restore-keys: |
          cargo-target-${{ runner.os }}-${{ steps.rust-cache.outputs.rust_version }}-${{ steps.rust-cache.outputs.cargo_lock_hash }}
          cargo-target-${{ runner.os }}-${{ steps.rust-cache.outputs.rust_version }}-
          cargo-target-${{ runner.os }}-

    - name: Install wasm32-wasip1 target
      run: rustup target add wasm32-wasip1
      shell: bash
