name: 'Fetch PR Previews Artifact'
description: 'Fetches the latest PR previews artifact from either storybook-preview.yml or storybook-cleanup.yml workflows'
outputs:
  found:
    description: 'Whether the artifact was found'
    value: ${{ steps.get-pr-run.outputs.found }}
  run-id:
    description: 'The workflow run ID where the artifact was found'
    value: ${{ steps.get-pr-run.outputs.run_id }}
  workflow-name:
    description: 'The name of the workflow where the artifact was found'
    value: ${{ steps.get-pr-run.outputs.workflow_name }}
runs:
  using: 'composite'
  steps:
    - name: Get latest PR previews from previous runs
      id: get-pr-run
      uses: actions/github-script@v7
      with:
        script: |
          // Get previous successful runs from both preview and cleanup workflows
          const [previewRuns, cleanupRuns] = await Promise.all([
            github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '.github/workflows/storybook-preview.yml',
              status: 'success',
              per_page: 5
            }),
            github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '.github/workflows/storybook-cleanup.yml',
              status: 'success',
              per_page: 5
            })
          ]);

          // Combine and sort by created_at to find the most recent
          const allRuns = [
            ...previewRuns.data.workflow_runs,
            ...cleanupRuns.data.workflow_runs
          ].sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

          // Get the most recent successful run
          const targetRun = allRuns[0];

          if (targetRun) {
            const runId = targetRun.id;
            console.log(`Found PR previews run: ${runId} from ${targetRun.name}`);
            core.setOutput('run_id', runId);
            core.setOutput('found', 'true');
            core.setOutput('workflow_name', targetRun.name);
          } else {
            console.log('No PR preview runs found');
            core.setOutput('found', 'false');
          }

    - name: Download PR previews artifact
      if: steps.get-pr-run.outputs.found == 'true'
      uses: actions/download-artifact@v5
      with:
        name: storybook-pr-previews
        path: ./pr-previews
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: ${{ steps.get-pr-run.outputs.run_id }}
      continue-on-error: true
