name: Storybook

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 22.x

concurrency:
  group: storybook-deployment
  cancel-in-progress: false

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Setup pnpm with cache
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: pnpm build-storybook

      - name: Upload main storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-main
          path: ./storybook-static
          retention-days: 30

      - name: Fetch PR previews
        uses: ./.github/actions/fetch-pr-previews

      - name: Combine main storybook with PR previews
        run: |
          mkdir -p ./combined-pages

          # Add main storybook
          cp -r ./storybook-static/* ./combined-pages/

          # Add PR previews if they exist
          if [ -d ./pr-previews ]; then
            cp -r ./pr-previews ./combined-pages/pr
            echo "Added PR previews to combined pages"
          else
            echo "No PR previews found"
          fi

      - name: Upload combined pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './combined-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
