name: Storybook Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: 22.x

concurrency:
  group: storybook-deployment
  cancel-in-progress: false

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  issues: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5

      - name: Setup pnpm with cache
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Get latest main storybook workflow run
        id: get-main-run
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '.github/workflows/storybook.yml',
              branch: 'main',
              status: 'success',
              per_page: 1
            });

            if (runs.data.workflow_runs.length > 0) {
              const runId = runs.data.workflow_runs[0].id;
              console.log(`Found main storybook run: ${runId}`);
              core.setOutput('run_id', runId);
              core.setOutput('found', 'true');
            } else {
              console.log('No main storybook runs found');
              core.setOutput('found', 'false');
            }

      - name: Download main storybook artifact
        if: steps.get-main-run.outputs.found == 'true'
        uses: actions/download-artifact@v5
        continue-on-error: true
        with:
          name: storybook-main
          path: ./storybook-static-main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-main-run.outputs.run_id }}

      - name: Get latest PR previews from previous runs
        id: get-previous-pr-run
        uses: actions/github-script@v7
        with:
          script: |
            // Get previous successful runs of this workflow (excluding current)
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '.github/workflows/storybook-preview.yml',
              status: 'success',
              per_page: 10
            });

            // Find the most recent run that's not the current one
            const currentRunId = context.runId;
            const previousRun = runs.data.workflow_runs.find(run => run.id !== currentRunId);

            if (previousRun) {
              const runId = previousRun.id;
              console.log(`Found previous PR preview run: ${runId}`);
              core.setOutput('run_id', runId);
              core.setOutput('found', 'true');
            } else {
              console.log('No previous PR preview runs found');
              core.setOutput('found', 'false');
            }

      - name: Download previous PR previews artifact
        if: steps.get-previous-pr-run.outputs.found == 'true'
        uses: actions/download-artifact@v5
        continue-on-error: true
        with:
          name: storybook-pr-previews
          path: ./pr-previews
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-previous-pr-run.outputs.run_id }}

      - name: Add current PR storybook to previews
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Create or update PR previews directory
          mkdir -p ./pr-previews

          # Add this PR's storybook
          rm -rf ./pr-previews/${PR_NUMBER}
          mkdir -p ./pr-previews/${PR_NUMBER}
          cp -r ./storybook-static/* ./pr-previews/${PR_NUMBER}/
          echo "Added PR #${PR_NUMBER} preview"

      - name: Upload PR previews artifact
        uses: actions/upload-artifact@v5
        with:
          name: storybook-pr-previews
          path: ./pr-previews
          retention-days: 30

      - name: Combine main storybook with PR previews
        run: |
          mkdir -p ./combined-pages

          # Add main storybook if it exists
          if [ -d ./storybook-static-main ]; then
            cp -r ./storybook-static-main/* ./combined-pages/
            echo "Added main storybook"
          else
            echo "Warning: No main storybook found. Main branch needs to be deployed."
          fi

          # Add all PR previews
          if [ -d ./pr-previews ]; then
            cp -r ./pr-previews ./combined-pages/pr
            echo "Added PR previews to combined pages"
          fi

      - name: Upload combined pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './combined-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Post deployment comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm bot storybook \
            ${{ github.repository_owner }} \
            ${{ github.event.repository.name }} \
            ${{ github.event.pull_request.number }}
